name: 'ReadYaml'
runtime: 'python3.6'
s3_bucket: 'nicor-dev'
s3_key: 'deployments/lambdas/read_yaml.zip'
libs:
  - dateutil
  - pandas
  - py
  - pytz
  - six
  - yaml # it's the folder name for pyyaml
